### ISSUE TITLE
[ipgetter2.py] [line 212] NoneType Object has no attribute 'Upper'

### ISSUE THREAD

**Issue by k-amin07** [starofrainnight/ipgetter2#3]
* ipgetter2 version: 1.1.9
* Python version: 3.6.5
* Operating System: Deepin 15.11 (based on Debian)

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did
I have a script, which fetches my IP address from ipgetter2, to be used with geolite. Once in a while, the script crashes at line 212 of ipgetter2.py in function "get_from()"

```
Paste the command(s) you ran and the output.

from ipgetter2 import IPGetter
getter = IPGetter()
myIPObj = getter.get()
myIP = myIPObj.v4.compressed

If there was a crash, please include the traceback here.

Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/advention/.local/lib/python3.6/site-packages/ipgetter2/ipgetter2.py", line 252, in fetch_address_thread
    address = self.get_from(url)
  File "/home/advention/.local/lib/python3.6/site-packages/ipgetter2/ipgetter2.py", line 212, in get_from
    if guessed["encoding"].upper() == "GB2312":
AttributeError: 'NoneType' object has no attribute 'upper'
```
I believe adding a try/except block might resolve the issue.

**Comment by starofrainnight** [comment]
Thanks for your issue report, I will take a look later :)
