### ISSUE TITLE
IP_URLS error

### ISSUE THREAD

**Issue by zazayaya** [starofrainnight/ipgetter2#4]
* ipgetter2 version:
* Python version:
* Operating System:

### Description
http://www.taobao.com/help/getip.php
return taobao callback ip not client ip

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by starofrainnight** [comment]
Thanks your reports, I will remove it in next release.
