### ISSUE TITLE
Link to docs broken

### ISSUE THREAD

**Issue by pierrecorsini** [starofrainnight/ipgetter2#6]
On the repo the link to docs seems broken:

The link:
![image](https://user-images.githubusercontent.com/50719398/96365019-b9054000-1135-11eb-8cc7-3eb12a6fff75.png)

Links to:

![image](https://user-images.githubusercontent.com/50719398/96365015-b3a7f580-1135-11eb-970d-4c81fc2472ad.png)

**Comment by starofrainnight** [comment]
Yep, I will remove the doc link from README, that link just generated by the python package template.
